DROP TABLE if exists user;
DROP TABLE if exists capital;
DROP TABLE if exists post;

CREATE TABLE `user`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `first_name` VARCHAR(255) NOT NULL,
    `last_name` VARCHAR(255) NOT NULL,
    `username` VARCHAR(255) NOT NULL,
    `password` CHAR(255) NOT NULL
);
CREATE TABLE `capital`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `country` VARCHAR(255) NOT NULL,
    `population` BIGINT NOT NULL,
    `language` VARCHAR(255) NOT NULL,
    `url` VARCHAR(255) NOT NULL,
    `currency` VARCHAR(30) NOT NULL,
    `description_title` VARCHAR(100) NOT NULL,
    `description_subtitle_1` VARCHAR(100) NOT NULL,
    `description_text_1` LONGTEXT NOT NULL,
    `description_subtitle_2` VARCHAR(100) NOT NULL,
    `description_text_2` LONGTEXT NOT NULL,
    `description_subtitle_3` VARCHAR(100) NOT NULL,
    `description_text_3` LONGTEXT NOT NULL,
);
CREATE TABLE `post`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `capital_id` INT UNSIGNED NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` LONGTEXT NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `local` TINYINT(1) NOT NULL,
    `date` DATE NOT NULL
);
ALTER TABLE
    `post` ADD CONSTRAINT `post_user_id_foreign` FOREIGN KEY(`user_id`) REFERENCES `user`(`id`);
ALTER TABLE
    `post` ADD CONSTRAINT `post_capital_id_foreign` FOREIGN KEY(`capital_id`) REFERENCES `capital`(`id`);

INSERT INTO `capital` 
    (`name`, 
    `country`, 
    `population`, 
    `language`, 
    `url`, 
    `currency`, 
    `description_title`, 
    `description_subtitle_1`, 
    `description_text_1`, 
    `description_subtitle_2`, 
    `description_text_2`, 
    `description_subtitle_3`, 
    `description_text_3`)
VALUES
    (
        `Amsterdam`, 
        `the Netherlands`, 
        825080, 
        `Dutch`, 
        `https://images.pexels.com/photos/14419920/pexels-photo-14419920.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1`,
        `euro (EUR)`, 
        `Amsterdam Unveiled: A Journey Through Culture and Charm`,
        `Navigating Amsterdam's Cultural Tapestry`,
        `Amsterdam's cultural diversity is a true testament to its status as a global city. From the iconic Rijksmuseum, housing masterpieces by Dutch masters like Rembrandt and Vermeer, to the thought-provoking Anne Frank House, where poignant stories of wartime resilience come to life, this guide provides insights that help you delve into the city's cultural treasures. Discover the intertwining threads of Amsterdam's past and present as you wander along its charming streets, passing by centuries-old buildings and lively markets. Immerse yourself in the Van Gogh Museum, where the genius of the renowned artist unfolds in a mesmerizing collection of his finest works, and embrace the vibrant nightlife that paints the city with a modern, energetic palette.`,
        `Beyond Canals: Unveiling Hidden Gems`,
        `While Amsterdam's iconic canals are a sight to behold, there's more to explore beyond their beauty. Discover the quaint neighborhood of Jordaan, where artisan boutiques and cozy cafes beckon, offering a taste of local life. Indulge in the delectable culinary scene, from hearty Dutch pancakes to tantalizing Indonesian rijsttafel. Uncover insider knowledge as you admire the innovative architecture at NDSM Wharf or cycle through Vondelpark, where nature's tranquility offers a respite from the urban hustle.`,
        `Discover Amsterdam's Must-Visit Gems`,
        `No visit to Amsterdam is complete without exploring its key attractions. Wander through the historic streets of Dam Square, where the Royal Palace and the Nieuwe Kerk stand as testaments to the city's regal past. Embark on a leisurely canal cruise to admire the charming canal houses and iconic bridges that have earned Amsterdam its «Venice of the North» nickname. Delight in the blooms at Keukenhof Gardens during tulip season, a dazzling display of vibrant colors that epitomizes Dutch springtime. And don't forget to soak in the cultural ambiance of Leidseplein, a lively square adorned with theaters, cafes, and street performances. As you traverse these key sites, Amsterdam's allure and enchantment will surely leave an indelible mark on your journey.`
    ),
    (
        `Andorra la Vella`,
        `Andorra`,
        22205,
        `Catalan`,
        `https://images.pexels.com/photos/5828197/pexels-photo-5828197.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1`,
        `euro (EUR)`,
        `Andorra Unveiled: Exploring the Heart of the Pyrenees`,
        `Navigating Andorra la Vella's Unique Charms`,
        `Nestled among the breathtaking Pyrenees mountains, Andorra la Vella stands as a captivating gem, inviting you to embark on an unforgettable journey through its rich culture and natural beauty. This guide leads you through the enchanting streets of the capital city, offering insights that reveal the tapestry of Andorra's history, traditions, and modern allure. From the iconic Casa de la Vall, a historic parliament building, to the inspiring Església de Sant Esteve, a Romanesque church that has witnessed centuries of devotion, this guide opens doors to Andorra la Vella's cultural treasures. Roam through charming alleys and bustling markets, discover the captivating stories behind its landmarks, and immerse yourself in a city that beautifully harmonizes tradition with the contemporary.`,
        `Beyond City Limits: Exploring Natural Wonders`,
        `While Andorra la Vella is a delightful urban hub, there's a world of natural wonders waiting to be explored just beyond its limits. Journey into the Pyrenees and embrace the exhilarating outdoor experiences that Andorra is renowned for. Lace up your hiking boots and trek along scenic trails that reveal panoramic vistas of rugged peaks and lush valleys. For thrill-seekers, winter brings the promise of world-class skiing and snowboarding on pristine slopes. As you venture through the surrounding landscapes, from the calming beauty of Engolasters Lake to the adventurous pursuits of Vallnord Bike Park, you'll discover that Andorra's allure extends far beyond the cityscape.`,
        `Embracing Andorra la Vella's Essence`,
        `To truly seize the essence of Andorra la Vella, you must immerse yourself in its unique blend of history, culture, and nature. Whether you're strolling through the vibrant Meritxell Avenue, where boutiques and cafes beckon, or exploring the Casa de la Vall's chambers that have witnessed the evolution of Andorra's governance, every step unveils a piece of this city's captivating story. Allow the aromas of traditional Andorran cuisine to guide you to local eateries, where hearty dishes like trinxat and escudella reflect the essence of the land. And, of course, no exploration is complete without a visit to Caldea, Europe's largest thermal spa, where relaxation and rejuvenation merge amidst modern architectural wonders. As you embrace the beauty and soul of Andorra la Vella, you'll discover that this small capital holds an irresistible allure that leaves a lasting imprint on your journey through the Pyrenees.`
    ),
    (
        `Athens`,
        `Greece`,
        664046,
        `Greek`,
        `https://images.pexels.com/photos/15238869/pexels-photo-15238869/free-photo-of-vacances-fita-estiu-viatjar.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1`,
        `euro (EUR)`,
        `Athens Unveiled: Embarking on a Journey through Ancient Splendor`,
        `Navigating Athens' Historical and Cultural Tapestry`,
        `With a history that spans millennia, Athens stands as a beacon of ancient splendor and modern vitality. This guide invites you to traverse the captivating streets of Greece's capital, where echoes of philosophers, poets, and warriors resound through the ruins. Explore the awe-inspiring Acropolis, where the Parthenon reigns majestically over the city, and delve into the treasures of the National Archaeological Museum, home to a breathtaking collection that chronicles Greece's rich past. Wander through the bustling Plaka district, where charming alleys and traditional tavernas create an atmosphere that bridges the gap between the past and the present. Athens' cultural tapestry comes to life as you journey from the historic Odeon of Herodes Atticus to the vibrant Monastiraki Square, revealing a city that proudly wears its history on its sleeve.`,
        `Beyond Ancient Ruins: Embracing the Modern Spirit`,
        `While Athens is renowned for its ancient heritage, its modern spirit is equally captivating. Immerse yourself in the vibrant atmosphere of Syntagma Square, where the Hellenic Parliament and the Tomb of the Unknown Soldier stand as symbols of Greece's enduring democracy. Stroll through the Athens Central Market, where colorful displays of fresh produce, spices, and local delicacies showcase the city's culinary diversity. Indulge in the arts at the Stavros Niarchos Foundation Cultural Center, a contemporary marvel that hosts world-class performances and exhibitions. As you explore the modern facets of Athens, you'll discover a city that gracefully harmonizes its storied past with its dynamic present.`,
        `Embracing Greek Flavors and Sunset Serenity`,
        `To truly unveil Athens' essence, you must delve into its treasures and immerse yourself in its vibrant culture. Savor the flavors of Greek cuisine, from the tangy allure of tzatziki to the savory embrace of moussaka. Traverse the historic Agora, once the heart of Athenian life, and imagine the philosophical debates that once echoed through its columns. Wander through the charming neighborhoods of Anafiotika and Exarcheia, each offering a distinct perspective on the city's character. And don't miss the opportunity to witness a breathtaking sunset from the summit of Lycabettus Hill, casting a golden glow over the city that has inspired poets and dreamers for centuries. Athens' allure is boundless, inviting you to embark on a journey that weaves together ancient marvels and contemporary wonders, leaving an indelible mark on your exploration of Greece's captivating capital.`
    ),
    (
        `Belgrade`,
        `Republic of Serbia`,
        1387422,
        `Serbian`,
        `https://images.unsplash.com/photo-1613601740367-410ae03b2ec7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80`,
        `dinar (RSD)`,
        `Belgrade Unveiled: Embracing the Soul of the Balkans`,
        `Navigating Belgrade's Historic and Cultural Mosaic`,
        `At the crossroads of the Balkans, Belgrade beckons with a rich tapestry of history, culture, and resilience. This guide invites you to traverse the dynamic streets of Serbia's capital, where the confluence of influences has shaped a city that wears its scars and triumphs proudly. Explore the formidable Kalemegdan Fortress, where centuries of conquests and battles have left their mark, and venture into the depths of the Belgrade Underground, a labyrinth of tunnels that whispers tales of past eras. Delve into the heart of Belgrade's creative scene at the Mikser House, a hub for art, design, and innovation, and wander through the historic Skadarlija district, where cobblestone streets and traditional kafanas invite you to relish the city's bohemian spirit.`,
        `Beyond Urban Charms: Discovering Natural Oases`,
        `While Belgrade's urban charms are captivating, there's a world of natural beauty awaiting your exploration. Embrace the tranquility of Ada Ciganlija, a lush peninsula surrounded by the shimmering waters of Lake Sava, offering a perfect escape for leisure and recreation. Discover the majesty of Avala Mountain, where the iconic Avala Tower offers panoramic views of the city and beyond. Or venture to the confluence of the Sava and Danube rivers, where the Great War Island's wetlands provide a haven for diverse wildlife. Amidst the city's hustle and bustle, these natural oases offer a serene respite that highlights the harmonious blend of urban and natural elements that define Belgrade.`,
        `Market Buzz and Nocturnal Revelry`,
        `To truly unveil Belgrade's essence, you must immerse yourself in its captivating character and diverse spirit. Indulge in the bold flavors of Serbian cuisine, from hearty pljeskavica to the comforting embrace of sarma. Engage with the locals at the bustling Kalenic Market, where the vibrancy of daily life unfolds in a colorful array of produce and artisanal goods. Explore the Nikola Tesla Museum, a tribute to the visionary inventor whose legacy resonates through the city's veins. And, as night falls, experience the renowned Belgrade nightlife, where the beats of its music scene reverberate through riverside clubs and hidden bohemian venues. Belgrade's allure lies in its ability to be both a historical crossroads and a modern playground, inviting you to uncover its layers and celebrate its unbreakable spirit as you navigate its captivating streets.`
    ),
    (
        `Berlin`,
        `Germany`,
        3644826,
        `German`,
        `https://images.pexels.com/photos/9392358/pexels-photo-9392358.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1`,
        `euro (EUR)`,
        `Berlin Unveiled: A Fusion of History and Modernity`,
        `Navigating Berlin's Historical and Cultural Kaleidoscope`,
        `Berlin, a city steeped in history and pulsating with modern energy, invites you to embark on a captivating journey through its multifaceted streets. This guide leads you through the remnants of the Berlin Wall, a poignant symbol of the city's divided past, and into the grandeur of the Brandenburg Gate, an emblem of unity and rebirth. Explore the somber yet powerful Holocaust Memorial, a testament to remembrance and reflection, and indulge in the world-class art collections of Museum Island, a treasure trove that spans centuries and styles. Traverse the charming lanes of Nikolaiviertel, Berlin's oldest district, and immerse yourself in the creativity and innovation that thrive within the urban canvas of this remarkable capital.`,
        `Beyond Urban Frontiers: Embracing Modern Vistas`,
        `While Berlin's historical landmarks are captivating, the city's modern spirit offers a contrasting allure. Experience the architectural wonder of the Reichstag Building, where historic significance merges seamlessly with contemporary design. Stroll along the trendy Hackescher Markt, a district where art galleries, boutiques, and cafés create an artistic ambiance. Delve into the dynamic atmosphere of Potsdamer Platz, a hub of entertainment and commerce that reflects Berlin's ever-evolving identity. Amidst the city's bustling streets, discover the East Side Gallery, an open-air gallery that adorns a surviving stretch of the Berlin Wall with vibrant murals, representing a collective expression of hope and transformation.`,
        `Embarking on Berlin's Cultural Odyssey`,
        `To truly embrace Berlin's essence, you must immerse yourself in its vibrant culture and multifaceted character. Relish the culinary diversity that graces the city, from traditional currywurst to international fusion cuisine. Engage with the locals at the Mauerpark Flea Market, where vintage treasures and musical performances create an electric atmosphere. Explore the technological wonders of the Futurium, a museum that delves into the possibilities of tomorrow. And as the day transitions into night, venture into the heart of Berlin's nightlife, where a myriad of clubs, from historic venues to cutting-edge spaces, offer an unforgettable nocturnal adventure. Berlin's allure lies in its ability to bridge the gap between its tumultuous past and its vibrant present, inviting you to unravel its layers and celebrate its continuous journey of reinvention.`
    ),
    (
        `Bern`,
        `Switzerland`,
        134794,
        `German, French`,
        `https://images.pexels.com/photos/9214052/pexels-photo-9214052.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1`,
        `franc (CHF)`,
        `Bern Unveiled: Where History and Modernity Converge`,
        `Navigating Bern's Historical and Cultural Treasures`,
        `Bern, the charming capital of Switzerland, extends a warm invitation to embark on a captivating journey through its rich history and vibrant present. This guide leads you through the iconic Zytglogge clock tower, a living testament to medieval craftsmanship, and into the grandeur of the Federal Palace, where the country's democracy takes center stage. Explore the cobbled streets of the Old Town, a UNESCO World Heritage site, and immerse yourself in the cultural treasures of the Bern Historical Museum, where Swiss heritage comes to life through art and artifacts. Wander along the Aare River, where nature's serenity blends harmoniously with the city's architectural elegance, and uncover the essence of Bern's timeless allure.`,
        `Beyond the Facade: Discovering Modern Charms`,
        `While Bern's historical landmarks hold undeniable allure, the city's modernity offers a compelling counterpoint. Experience the immersive wonder of the Zentrum Paul Klee, a museum dedicated to the iconic Swiss painter, where innovative exhibitions captivate the senses. Stroll through the lively Bundesplatz, a central square that transforms with the seasons, hosting markets, festivals, and political gatherings. Delve into the vibrant culture of Bern's «Matte» district, where local eateries, artisan boutiques, and art studios converge, offering a glimpse into the contemporary pulse of the city. Amidst the architectural splendor of Bern, modern facets come to life, adding layers of intrigue to your exploration.`,
        `Embracing Bern's Flavors and Traditions`,
        `To fully embrace Bern's essence, you must savor its culinary delights and partake in its time-honored traditions. Indulge in the Swiss fondue experience, where melted cheese becomes a communal delight, or sample Bern's delectable «Älplermagronen», a comforting dish that embodies the region's Alpine heritage. Engage with the locals at the Federal Palace's weekly market, where fresh produce and artisanal creations thrive. Immerse yourself in the city's Fasnacht carnival, a lively celebration of music, costumes, and merriment. As the sun sets over the medieval skyline, relish the tranquil beauty of the Rosengarten, a rose garden that offers panoramic views of Bern's rooftops and distant peaks. Bern's allure lies in its harmonious blend of past and present, inviting you to immerse yourself in its multifaceted charm and create lasting memories in the heart of Switzerland.`
    ),
    (
        `Bratislava`,
        `Slovakia`,
        435296,
        `Slovak`,
        `https://images.pexels.com/photos/10137863/pexels-photo-10137863.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1`,
        `euro (EUR)`,
        `Bratislava Unveiled: Where Past Meets Present with Elegance`,
        `Navigating Bratislava's Historical and Cultural Splendor`,
        `Bratislava, the capital of Slovakia, extends a warm invitation to explore its enchanting blend of history and modernity. This guide leads you through the medieval charm of the Bratislava Castle, a silent witness to centuries of transformation, and into the heart of St. Martin's Cathedral, a testament to architectural mastery and spiritual significance. Immerse yourself in the captivating atmosphere of the Old Town, where cobblestone streets lead to quaint squares adorned with elegant facades. Discover the Slovak National Theatre, a cultural beacon that offers artistic performances against a backdrop of grandeur. As you wander along the Danube River, the harmony between the city's storied past and its vibrant present comes to life, offering a glimpse into Bratislava's enduring allure.`,
        `Beyond the Facade: Embracing Modern Vibes`,
        `While Bratislava's historical gems are captivating, the city's modern spirit adds a dynamic dimension to your journey. Experience the innovative design of the UFO Observation Deck, an architectural marvel that provides panoramic views of the city and beyond. Stroll through Eurovea, a modern riverside complex where shopping, dining, and entertainment converge seamlessly. Delve into the art scene at the Nedbalka Gallery, where Slovak contemporary art takes center stage, offering a fresh perspective on the city's creative vitality. Amidst the historical charm, Bratislava's modernity offers a delightful contrast that enriches your exploration.`,
        `Embracing Bratislava's Flavors and Traditions`,
        `To fully embrace Bratislava's essence, immerse yourself in its culinary delights and cherished traditions. Savor traditional Slovak dishes such as «bryndzové halušky», where dumplings and sheep's cheese create a hearty delight, or indulge in the sweet pleasures of a «Rusín» pastry. Engage with the locals at the bustling farmers' markets, where regional produce and handicrafts showcase the city's authenticity. Immerse yourself in the vibrant atmosphere of Bratislava's annual Coronation Celebration, a lively reenactment of historical events complete with period costumes and festivities. As the sun sets behind Bratislava Castle, take a leisurely stroll along the Danube promenade, where the illuminated cityscape mirrors the harmony between its storied history and its vibrant present. Bratislava's allure lies in its ability to seamlessly blend the old with the new, inviting you to uncover its layers and create cherished memories in the heart of Slovakia.`
    ),
    (
        `Brussels`,
        `Belgium`,
        177307,
        `French, Dutch`,
        `https://images.pexels.com/photos/3847431/pexels-photo-3847431.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1`,
        `euro (EUR)`,
        `Brussels Unveiled: Embracing Belgium's Multicultural Heart`,
        `Navigating Brussels' Historical and Cultural Mosaic`,
        `Brussels, the captivating heart of Belgium and the European Union, invites you on a remarkable journey that weaves together history and diversity. This guide leads you through the architectural splendor of the Grand Place, a UNESCO World Heritage site, and into the inspiring realm of the Atomium, a futuristic monument that symbolizes progress and unity. Wander the cobbled streets of the Sablon district, where historic charm meets contemporary art galleries, and bask in the elegance of the Royal Palace, a regal masterpiece nestled in the heart of the city. As you explore the vibrant neighborhoods, each with its own distinct character, you'll come to appreciate how Brussels seamlessly melds its storied past with the multicultural tapestry that defines its present.`,
        `Beyond the Facade: Embracing Global Vibes`,
        `While Brussels' historical landmarks are captivating, the city's international essence offers an exciting twist to your exploration. Immerse yourself in the vibrant atmosphere of the European Quarter, where modern architecture houses institutions that shape the continent's future. Stroll through Parc du Cinquantenaire, where the grand triumphal arch stands as a testament to Belgium's rich heritage. Delve into the avant-garde scene at Wiels Contemporary Art Centre, where thought-provoking exhibitions redefine artistic boundaries. Amidst the city's historical grandeur, Brussels' global perspective adds a layer of intrigue that invites you to expand your horizons.`,
        `Embracing Brussels' Flavors and Traditions`,
        `To fully embrace Brussels' essence, immerse yourself in its culinary delights and cherished customs. Delight in the «gaufres de Liège», a treat of fluffy waffles adorned with caramelized sugar, or explore the world of Belgian chocolates, where artistry meets indulgence. Engage with the locals at the lively Marolles Flea Market, where vintage treasures and eclectic trinkets tell stories of bygone eras. Immerse yourself in the festive spirit of the biennial Flower Carpet event, where the Grand Place transforms into a fragrant tapestry of blossoms. As the sun sets over the city's enchanting landmarks, savor a leisurely dinner at a traditional brasserie, sipping on «gueuze» while relishing the fusion of flavors that mirror Brussels' cultural amalgamation. Brussels' allure lies in its ability to be a meeting point of cultures, a place where the old and the new, the local and the global, converge harmoniously, inviting you to unravel its layers and create lasting memories at the heart of Europe.`
    ),
    (
        `Bucharest`,
        `Romania`,
        1823526,
        `Romanian`,
        `https://images.unsplash.com/photo-1643786852373-d3093da7a40d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1544&q=80`,
        `leu (RON)`,
        `Bucharest Unveiled: Embracing Romania's Dynamic Capital`,
        `Navigating Bucharest's Historical and Cultural Splendor`,
        `Bucharest, the dynamic capital of Romania, beckons you to embark on a captivating journey through its rich history and vibrant culture. This guide leads you through the opulent halls of the Palace of the Parliament, an architectural marvel that tells the story of a nation's aspirations. Venture into the heart of the Old Town, where centuries-old churches and charming streets evoke a sense of nostalgia. Discover the artistry of the Romanian Athenaeum, a cultural beacon that hosts symphonies and performances, and wander through Herastrau Park, where nature's tranquility offers respite amidst the urban hustle. As you explore Bucharest's diverse neighborhoods and landmarks, you'll uncover the essence of a city that blends tradition with modernity.`,
        `Beyond the Facade: Embracing Contemporary Vibes`,
        `While Bucharest's historical charm is alluring, the city's contemporary pulse offers a fascinating contrast. Immerse yourself in the creative atmosphere of the National Museum of Contemporary Art, where thought-provoking exhibitions redefine artistic boundaries. Stroll along Victoriei Avenue, where modern boutiques and cafes converge with historic architecture. Delve into the trendy Lipscani district, a hub of art, design, and entertainment, where the spirit of innovation thrives. Amidst Bucharest's architectural diversity, the city's contemporary spirit adds a layer of excitement to your exploration.`,
        `Embracing Bucharest's Flavors and Traditions`,
        `To fully embrace Bucharest's essence, indulge in its culinary treasures and cherished customs. Savor the «mămăligă», a traditional dish of polenta served with various accompaniments, or delight in the iconic «sarmale», cabbage rolls filled with flavorful mixtures. Engage with the locals at the bustling Obor Market, where a colorful array of produce and artisanal goods reflects Bucharest's authenticity. Immerse yourself in the vibrant energy of the annual George Enescu International Festival, a celebration of classical music that echoes through the city's streets. As the sun sets over the majestic Parliament Palace, join the locals in a leisurely evening stroll along the Dâmbovița River, where the city's lights shimmer on the water's surface, epitomizing the fusion of Bucharest's past, present, and future. Bucharest's allure lies in its ability to be a captivating blend of old-world charm and contemporary spirit, inviting you to uncover its layers and create unforgettable memories in the heart of Romania.`
    ),
    (
        `Budapest`,
        `Hungary`,
        1737026,
        `Hungarian`,
        `https://images.pexels.com/photos/15552883/pexels-photo-15552883/free-photo-of-hungarian-parliament-building.jpeg`,
        `forint (HUF)`,
        `Budapest Unveiled: Embracing Hungary's Enchanting Capital`,
        `Navigating Budapest's Historical and Cultural Splendor`,
        `Budapest, the enchanting capital of Hungary, extends a warm invitation to embark on a captivating journey through its rich history and vibrant culture. This guide leads you through the majestic expanse of Buda Castle, perched atop Castle Hill, and into the ornate beauty of the Hungarian Parliament Building, a symbol of national pride. Wander through the charming alleys of the Castle District, where medieval charm meets modern boutiques, and immerse yourself in the artistic riches of the Hungarian National Museum. Discover the thermal wonders of Széchenyi Bath, a testament to Budapest's spa heritage, and stroll along the Danube Promenade, where the river's embrace showcases the city's enduring allure.`,
        `Beyond the Facade: Embracing Contemporary Vibes`,
        `While Budapest's historical allure is captivating, the city's contemporary energy offers an exciting contrast. Immerse yourself in the innovative realm of Müpa Budapest, a cultural complex that hosts a diverse array of artistic performances and exhibitions. Stroll along the bustling Váci Street, a hub of shopping and entertainment that blends tradition with modernity. Delve into the creative heart of the Jewish Quarter, where street art and ruin bars create a dynamic urban canvas. Amidst Budapest's architectural splendor, the city's modern pulse adds an extra layer of excitement to your exploration.`,
        `Embracing Budapest's Flavors and Traditions`,
        `To fully embrace Budapest's essence, indulge in its culinary treasures and time-honored customs. Savor the iconic «gulyás», a hearty Hungarian stew, or delight in the mouthwatering pastries of a traditional Hungarian bakery. Engage with the locals at the bustling Great Market Hall, where the scents and colors of fresh produce and handicrafts create a vibrant atmosphere. Immerse yourself in the lively atmosphere of the Budapest Wine Festival, a celebration of Hungary's viticultural heritage. As the sun sets over the city's iconic Chain Bridge, take a leisurely evening cruise on the Danube River, where the illuminated skyline reflects the harmonious blend of Budapest's rich history and its modern spirit. Budapest's allure lies in its ability to be a captivating fusion of old-world charm and contemporary vibrancy, inviting you to uncover its layers and create cherished memories in the heart of Hungary.`
    ),
    (
        `Chisinau`,
        `Moldova`,
        339079,
        `Romanian`,
        `https://images.unsplash.com/photo-1629045951387-6d86eb2aad3d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80`,
        `leu (MDL)`,
        `Chisinau Unveiled: Embracing Moldova's Hidden Gem`,
        `Navigating Chisinau's Historical and Cultural Tapestry`,
        `Chisinau, the hidden gem of Moldova, invites you to embark on a journey through its rich history and vibrant culture. This guide leads you through the elegant beauty of the Nativity Cathedral, a symbol of spiritual significance, and into the heart of the Central Market, where local flavors and traditions converge. Wander through the serene Valea Morilor Park, a tranquil oasis amidst the city's hustle, and explore the cherished artifacts of the National Museum of Ethnography and Natural History. Discover the unique architecture of Chisinau's neighborhoods, each telling a story of resilience and transformation, and as you traverse the city's streets, you'll uncover the essence of a place that blends heritage with modernity.`,
        `Beyond the Facade: Embracing Local Charms`,
        `While Chisinau's historical landmarks are captivating, the city's local charm offers an intimate perspective. Immerse yourself in the warmth of Chisinau's hospitality as you explore its authentic cafes and markets, where the locals gather and stories are exchanged. Stroll through the lively Stefan cel Mare Park, a popular meeting place, and experience the vibrant arts scene at the National Opera and Ballet Theatre. Delve into the heart of Chisinau's winemaking tradition with a visit to a local winery, where you can taste the fruits of Moldova's centuries-old viticulture. Amidst Chisinau's unassuming beauty, its local character adds a layer of authenticity to your exploration.`,
        `Embracing Chisinau's Flavors and Traditions`,
        `To fully embrace Chisinau's essence, immerse yourself in its culinary treasures and cherished customs. Savor the «mămăligă», a traditional dish made from maize, often accompanied by local cheese and sour cream. Engage with the locals at the bustling Piata Centrala, where fresh produce and handicrafts create a vibrant atmosphere. Immerse yourself in the festive atmosphere of Moldova's wine festivals, celebrating the nation's rich winemaking heritage. As the sun sets over Chisinau's picturesque skyline, take a leisurely stroll along the charming Bulevardul Ştefan cel Mare, where the city's lights twinkle like stars, reflecting the seamless blend of old-world traditions and modern aspirations. Chisinau's allure lies in its ability to be a true reflection of Moldova's spirit, inviting you to uncover its layers and create lasting memories in this unique corner of the world.`
    ),
    (
        `Copenhagen`,
        `Denmark`,
        638790,
        `Danish`,
        `https://images.pexels.com/photos/5193476/pexels-photo-5193476.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1`,
        `krone (DKK)`,
        `Copenhagen Unveiled: Embracing Denmark's Coastal Gem`,
        `Navigating Copenhagen's Historical and Cultural Marvels`,
        `Copenhagen, Denmark's coastal treasure, beckons you to embark on a captivating journey through its rich history and contemporary culture. This guide leads you through the regal elegance of Rosenborg Castle, a testament to Danish royalty, and into the iconic embrace of The Little Mermaid sculpture, a symbol of fairy-tale inspiration. Wander through the vibrant Nyhavn Harbor, where colorful facades and lively waterfront cafes create an inviting atmosphere. Immerse yourself in the artistry of the Ny Carlsberg Glyptotek, where classical and modern masterpieces entwine, and explore the innovative architecture of the Black Diamond, home to the Royal Danish Library. As you explore Copenhagen's charming streets, you'll unveil the essence of a city that seamlessly blends tradition with modernity.`,
        `Beyond the Facade: Embracing Progressive Flair`,
        `While Copenhagen's historical charm is captivating, the city's progressive spirit offers a fascinating contrast. Immerse yourself in the sustainability-focused atmosphere of Christiania, a self-governing commune that embodies alternative living. Stroll through the vibrant Meatpacking District, where former slaughterhouses have transformed into a hub of creativity, offering galleries, boutiques, and eateries. Delve into the contemporary art scene at the Louisiana Museum of Modern Art, where coastal landscapes complement cutting-edge exhibitions. Amidst Copenhagen's architectural elegance, the city's forward-thinking approach adds an exciting layer to your exploration.`,
        `Embracing Copenhagen's Flavors and Traditions`,
        `To fully embrace Copenhagen's essence, immerse yourself in its culinary delights and cherished customs. Savor the beloved «smørrebrød», an open-faced sandwich adorned with an array of delectable toppings, or indulge in traditional Danish pastries, such as «wienerbrød». Engage with the locals at the bustling Torvehallerne market, where fresh produce, artisanal goods, and international flavors create a dynamic food scene. Immerse yourself in the festive atmosphere of Tivoli Gardens, one of the world's oldest amusement parks, where entertainment and enchantment intertwine. As the sun sets over Copenhagen's waterfront, enjoy a leisurely canal cruise, where the city's illuminated landmarks reflect the harmonious blend of its rich heritage and contemporary spirit. Copenhagen's allure lies in its ability to be a captivating juxtaposition of old-world charm and modern innovation, inviting you to uncover its layers and create cherished memories along the shores of Denmark.`
    ),
    (
        `Dublin`,
        `Ireland`,
        544197,
        `English, Irish`,
        `https://cdn.pixabay.com/photo/2021/11/16/17/33/dublin-6801635_1280.jpg`,
        `euro (EUR)`,
        `Dublin Explored: Embracing Ireland's Literary Heart`,
        `Navigating Dublin's Literary and Cultural Landscape`,
        `Dublin, the spirited heart of Ireland, invites you on a captivating journey through its rich literary heritage and vibrant culture. This guide leads you through the historic halls of Trinity College, where the Book of Kells and Long Room celebrate centuries of scholarly achievement. Venture into the cobblestone streets of Temple Bar, a cultural quarter where galleries, pubs, and street performances thrive, and immerse yourself in the pages of history at Dublin Castle. Explore the tranquility of St. Stephen's Green, an urban oasis that embodies Dublin's connection with nature, and uncover the city's essence as a beacon of Irish creativity and thought.`,
        `Beyond the Pages: Embracing Contemporary Charms`,
        `While Dublin's literary legacy is enchanting, the city's contemporary energy offers a vibrant contrast. Immerse yourself in the cosmopolitan atmosphere of Grafton Street, a bustling hub of shopping, entertainment, and people-watching. Stroll along the revitalized River Liffey, where modern architecture and innovative design reflect Dublin's evolving identity. Delve into the modern art scene at the Irish Museum of Modern Art, housed in the historic Royal Hospital Kilmainham. Amidst the city's historic cobblestones, Dublin's modern spirit adds a layer of excitement and exploration.`,
        `Embracing Dublin's Flavors and Traditions`,
        `To fully embrace Dublin's essence, indulge in its culinary treasures and cherished customs. Savor traditional Irish dishes like «coddle», a hearty stew, or the iconic «full Irish breakfast», a hearty morning feast. Engage with the locals at the vibrant Temple Bar Food Market, where a kaleidoscope of flavors and artisanal goods awaits. Immerse yourself in the convivial atmosphere of a traditional Irish pub, where live music and storytelling create a sense of community. As the sun sets over Dublin's iconic Ha'penny Bridge, take a leisurely stroll along the River Liffey's boardwalk, where the city's lights dance on the water's surface, reflecting the harmonious blend of Dublin's rich history and its contemporary vibrancy. Dublin's allure lies in its ability to be a living testament to the past and a canvas for modern expression, inviting you to uncover its layers and create treasured memories in the heart of Ireland.`
    ),
    (
        `Helsinki`,
        `Finland`,
        656920,
        `Finnish`,
        `https://images.pexels.com/photos/3581820/pexels-photo-3581820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1`,
        `euro (EUR)`,
        `Helsinki Explored: Embracing Finland's Nordic Charisma`,
        `Navigating Helsinki's Cultural and Architectural Landscape`,
        `Helsinki, the captivating capital of Finland, beckons you to embark on a captivating journey through its rich cultural tapestry and architectural splendor. This guide leads you through the neoclassical elegance of Senate Square, where the Helsinki Cathedral stands as a symbol of national identity, and into the contemporary brilliance of the Kamppi Chapel, a sanctuary of tranquility amidst the urban bustle. Wander through the vibrant Design District, where Finnish creativity thrives in boutiques, galleries, and cafes, and immerse yourself in the cultural treasures of the National Museum of Finland. Explore the serene beauty of Suomenlinna, a UNESCO World Heritage site spread across islands, and as you navigate Helsinki's diverse neighborhoods, you'll uncover the essence of a city that seamlessly blends tradition with modern innovation.`,
        `Beyond the Facades: Embracing Contemporary Charms`,
        `While Helsinki's historical landmarks are captivating, the city's modern spirit offers a captivating contrast. Immerse yourself in the innovative atmosphere of the Oodi Central Library, a hub of learning, creativity, and community. Stroll along the picturesque shores of the Baltic Sea, where modern urban planning meets natural beauty at the vibrant Hietaranta Beach. Delve into the modern art scene at the Kiasma Museum of Contemporary Art, where thought-provoking exhibitions redefine artistic boundaries. Amidst Helsinki's architectural gems, the city's contemporary flair adds an exciting layer to your exploration.`,
        `Embracing Helsinki's Flavors and Traditions`,
        `To fully embrace Helsinki's essence, indulge in its culinary treasures and cherished customs. Savor traditional Finnish dishes like «kalakukko», a savory fish pie, or «karjalanpiirakka», a Karelian pastry. Engage with the locals at the bustling Old Market Hall, where a tantalizing array of fresh produce, seafood, and local delicacies await. Immerse yourself in the joyous atmosphere of the Vappu festival, a celebration of spring and labor, where picnics, parades, and merriment fill the streets. As the sun sets over the serene Helsinki coastline, take a leisurely stroll along the Esplanade Park, where the city's lights twinkle like stars, reflecting the harmonious blend of Helsinki's rich heritage and its contemporary charm. Helsinki's allure lies in its ability to be a haven of tradition and a playground of modernity, inviting you to uncover its layers and create cherished memories in the heart of Finland.`
    ),
    (
        `Kiev`,
        `Ukrain`,
        2893215,
        `Ukranian`,
        `https://images.pexels.com/photos/12932192/pexels-photo-12932192.jpeg`,
        `hryvnia (UAH)`,
        `Kiev Explored: Embracing Ukraine's Historic Heart`,
        `Navigating Kiev's Cultural and Architectural Riches`,
        `Kiev, the historic heart of Ukraine, extends a warm invitation to embark on a captivating journey through its rich cultural tapestry and architectural wonders. This guide leads you through the golden domes of St. Sophia's Cathedral, a UNESCO World Heritage site that embodies centuries of spiritual significance, and into the grandeur of Kyiv Pechersk Lavra, a complex of monasteries and caves that stand as a testament to the nation's heritage. Wander through the charming streets of Andriyivsky Uzviz, where bohemian spirit meets artisanal treasures, and immerse yourself in the artistic treasures of the National Museum of Ukrainian History. Discover the tranquility of Mariyinsky Park, where nature and history intertwine, and as you traverse Kiev's neighborhoods, you'll unveil the essence of a city that embraces its past while looking toward the future.`,
        `Beyond the Facades: Embracing Contemporary Charms`,
        `While Kiev's historical allure is captivating, the city's contemporary energy adds a vibrant twist. Immerse yourself in the modernity of the Maidan Nezalezhnosti, Kiev's central square, where gatherings and events reflect the nation's aspirations. Stroll along Khreshchatyk Street, Kiev's main boulevard, where bustling shops, cafes, and vibrant street life create an energetic ambiance. Delve into the modern art scene at the PinchukArtCentre, where innovative exhibitions captivate the senses. Amidst Kiev's architectural marvels, the city's modern vibrancy adds an extra layer of intrigue to your exploration.`,
        `Embracing Kiev's Flavors and Traditions`,
        `To fully embrace Kiev's essence, indulge in its culinary treasures and cherished customs. Savor traditional Ukrainian dishes like «borscht», a hearty beet soup, or «varenyky», delicious dumplings with various fillings. Engage with the locals at the bustling Bessarabsky Market, where fresh produce and artisanal products create a vibrant tapestry of flavors. Immerse yourself in the festive atmosphere of the Vyshyvanka Festival, a celebration of traditional Ukrainian embroidery and culture. As the sun sets over the picturesque Dnipro River, take a leisurely walk along the Khreshchatyi Park, where the city's lights twinkle like stars, reflecting the harmonious blend of Kiev's rich history and its contemporary vitality. Kiev's allure lies in its ability to be a bridge between old and new, inviting you to uncover its layers and create cherished memories in the heart of Ukraine.`
    ),
    (
        `Lisbon`,
        `Portugal`,
        509564,
        `Portuguese`,
        `https://images.pexels.com/photos/4633656/pexels-photo-4633656.jpeg`,
        `euro (EUR)`,
        `Lisbon Explored: Embracing Portugal's Coastal Charm`,
        `Navigating Lisbon's Historical and Cultural Treasures`,
        `Lisbon, the captivating capital of Portugal, extends a warm invitation to embark on a captivating journey through its rich history and vibrant culture. This guide leads you through the iconic Belem Tower, a maritime marvel that tells tales of exploration, and into the enchanting interior of Jeronimos Monastery, a UNESCO World Heritage site that embodies centuries of spiritual significance. Wander through the narrow streets of Alfama, where traditional fado music and charming taverns create an intimate ambiance, and immerse yourself in the captivating collections of the National Museum of Ancient Art. Discover the breathtaking views from São Jorge Castle, where ancient walls stand as guardians of Lisbon's storied past, and as you explore the city's neighborhoods, you'll uncover the essence of a place that merges history with a modern outlook.`,
        `Beyond the Facades: Embracing Modern Vibes`,
        `While Lisbon's historical landmarks are captivating, the city's modern spirit offers an exciting contrast. Immerse yourself in the innovative atmosphere of the LX Factory, a creative hub housed in a former industrial complex, where art, design, and gastronomy flourish. Stroll along the waterfront at Parque das Nações, where modern architecture and leisure spaces harmonize with the Tagus River. Delve into the contemporary art scene at the Berardo Collection Museum, where international masterpieces provoke thought and dialogue. Amidst Lisbon's historic charm, the city's modernity offers a fresh layer of excitement to your exploration.`,
        `Embracing Lisbon's Flavors and Traditions`,
        `To fully embrace Lisbon's essence, indulge in its culinary treasures and cherished customs. Savor traditional Portuguese dishes like «bacalhau à Brás», a savory codfish creation, or «pasteis de nata», delectable custard tarts that are a true local delight. Engage with the locals at the bustling Mercado da Ribeira, where diverse food stalls and artisanal products create a vibrant tapestry of flavors. Immerse yourself in the festive atmosphere of Lisbon's traditional festivals, such as Santo António, a celebration of music, dance, and community spirit. As the sun sets over the tranquil waters of the Tagus, take a leisurely tram ride through the historic streets of Lisbon, where the city's illuminated landmarks reflect the harmonious blend of its rich heritage and its contemporary allure. Lisbon's allure lies in its ability to be a captivating fusion of past and present, inviting you to uncover its layers and create cherished memories along Portugal's stunning coastline.`
    ),
    (
        `Ljubljana`,
        `Slovenia`,
        285604,
        `Slovene`,
        `https://images.unsplash.com/photo-1599925355047-669e976bcd69?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80`,
        `euro (EUR)`,
        `Ljubljana Explored: Embracing Slovenia's Enchanting Capital`,
        `Navigating Ljubljana's Historical and Cultural Delights`,
        `Ljubljana, the enchanting capital of Slovenia, invites you on a captivating journey through its rich history and vibrant culture. This guide leads you through the charming alleys of the Old Town, where medieval architecture and picturesque squares exude a timeless allure, and into the splendor of Ljubljana Castle, perched on a hill overlooking the city. Wander through the vibrant atmosphere of Prešeren Square, where the iconic Triple Bridge connects the past and present, and immerse yourself in the artistry of the National Gallery of Slovenia. Discover the tranquility of Tivoli Park, a haven of greenery and art, and as you explore Ljubljana's neighborhoods, you'll uncover the essence of a city that celebrates tradition while embracing modernity.`,
        `Beyond the Facades: Embracing Local Charms`,
        `While Ljubljana's historical charm is captivating, the city's local character offers an intimate perspective. Immerse yourself in the warmth of Ljubljana's cafes, where locals gather for coffee and conversation, and stroll along the banks of the emerald-green Ljubljanica River, where outdoor markets and vibrant street art create a dynamic ambiance. Delve into the contemporary art scene at the Museum of Modern Art, where Slovenian and international works captivate the imagination. Amidst Ljubljana's architectural gems, the city's local vibrancy adds an extra layer of authenticity to your exploration.`,
        `Embracing Ljubljana's Flavors and Traditions`,
        `To fully embrace Ljubljana's essence, indulge in its culinary treasures and cherished customs. Savor traditional Slovenian dishes like «kranjska klobasa», a savory sausage, or «potica», a delectable nut-filled pastry. Engage with the locals at the bustling Central Market, where fresh produce, artisanal goods, and a bustling atmosphere reflect Ljubljana's authenticity. Immerse yourself in the festive atmosphere of Ljubljana Castle's Summer Nights, a cultural celebration of music, theater, and open-air gatherings. As the sun sets over the Ljubljana Castle's towers, take a leisurely boat cruise along the river, where the city's lights dance on the water's surface, reflecting the harmonious blend of Ljubljana's rich heritage and its local charm. Ljubljana's allure lies in its ability to be a captivating fusion of tradition and modernity, inviting you to uncover its layers and create cherished memories in the heart of Slovenia.`
    ),
    (
        `London`,
        `United Kingdom`,
        8538689,
        `English`,
        `https://images.pexels.com/photos/7245327/pexels-photo-7245327.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1`,
        `sterling (GBP)`,
        `London Explored: Embracing the United Kingdom's Cultural Melting Pot`,
        `Navigating London's Historical and Cultural Marvels`,
        `London, the vibrant capital of the United Kingdom, extends an open invitation to embark on a captivating journey through its rich history and diverse culture. This guide leads you through the regal elegance of Buckingham Palace, where centuries of monarchy come to life during the Changing of the Guard, and into the iconic embrace of the Tower of London, a medieval fortress that holds tales of intrigue and royalty. Wander through the bustling streets of Covent Garden, where street performers and artisanal markets create a lively atmosphere, and immerse yourself in the artistic treasures of the British Museum. Discover the serenity of Hyde Park, an expansive urban oasis where nature and city life harmonize, and as you traverse London's neighborhoods, you'll uncover the essence of a metropolis that seamlessly blends tradition with contemporary dynamism.`,
        `Beyond the Facades: Embracing Modern Vibes`,
        `While London's historical landmarks are captivating, the city's modern pulse offers an exciting contrast. Immerse yourself in the innovative spirit of the Tate Modern, a powerhouse of contemporary art housed in a former power station. Stroll along the vibrant Southbank, where cultural institutions, dining, and riverside views converge, and delve into the futuristic allure of the Shard's observation deck, offering panoramic views of London's iconic skyline. Amidst London's historic charm, the city's modernity adds an extra layer of excitement to your exploration.`,
        `Embracing London's Flavors and Traditions`,
        `To fully embrace London's essence, indulge in its culinary treasures and cherished customs. Savor classic British dishes like «fish and chips», a beloved comfort food, or «Afternoon Tea», an iconic tradition that blends elegance and indulgence. Engage with the locals at the bustling Borough Market, where a tapestry of international flavors and artisanal products create a culinary haven. Immerse yourself in the festive atmosphere of Notting Hill Carnival, a vibrant celebration of Caribbean culture that fills the streets with music and color. As the sun sets over the River Thames, take a leisurely stroll across the Millennium Bridge, where the city's lights twinkle like stars, reflecting the harmonious blend of London's storied past and its modern vibrancy. London's allure lies in its ability to be a captivating fusion of history and innovation, inviting you to uncover its layers and create cherished memories in this iconic global hub.`
    ),
    (
        ``,
        ``,
        ,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``
    ),
    (
        `Luxembourg`,
        `Luxembourg`,
        114303,
        `Luxembourgish, French, German`,
        `https://images.unsplash.com/photo-1588336899284-950764f07147?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80`,
        `euro (EUR)`,
        `Luxembourg City Explored: Embracing the Grand Duchy's Cultural Gem`,
        `Navigating Luxembourg City's Historical and Cultural Charms`,
        `Luxembourg City, the cultural gem of the Grand Duchy, welcomes you to embark on a captivating journey through its rich history and diverse heritage. This guide leads you through the impressive stronghold of Luxembourg Castle, where medieval walls and panoramic views offer a glimpse into the past, and into the elegant interior of the Grand Ducal Palace, a regal symbol of the nation. Wander through the charming streets of the Grund district, where cobblestone alleys and riverside cafes create a picturesque ambiance, and immerse yourself in the artistic treasures of the Luxembourg City History Museum. Discover the tranquility of Pétrusse Valley Park, a green oasis in the heart of the city, and as you explore Luxembourg City's neighborhoods, you'll uncover the essence of a place that honors tradition while embracing a modern spirit.`,
        `Beyond the Facades: Embracing Contemporary Charms`,
        `While Luxembourg City's historical allure is captivating, the city's contemporary energy offers an exciting contrast. Immerse yourself in the vibrant atmosphere of the Kirchberg district, a modern hub of architecture and commerce, where the European Court of Justice and other institutions stand as symbols of European unity. Stroll along the lively Rives de Clausen, a former industrial area transformed into a hotspot of nightlife and entertainment, and delve into the innovative realm of the MUDAM (Musée d'Art Moderne Grand-Duc Jean), where modern artworks challenge conventions. Amidst Luxembourg City's architectural splendor, its modern pulse adds an extra layer of excitement to your exploration.`,
        `Embracing Luxembourg City's Flavors and Traditions`,
        `To fully embrace Luxembourg City's essence, indulge in its culinary treasures and cherished customs. Savor traditional Luxembourgish dishes like «judd mat gaardebounen», a hearty smoked pork dish, or the iconic «Gromperekichelcher», potato fritters enjoyed at markets and celebrations. Engage with the locals at the bustling Grund Market, where fresh produce, local delicacies, and handmade crafts create a vibrant tapestry of flavors. Immerse yourself in the festive atmosphere of the Schueberfouer, one of Europe's oldest fairs, where lights, rides, and laughter fill the night air. As the sun sets over the Alzette River, take a leisurely walk along the Chemin de la Corniche, often referred to as «Europe's most beautiful balcony», where the city's lights twinkle in the distance, reflecting the harmonious blend of Luxembourg City's historical roots and its modern allure. Luxembourg City's allure lies in its ability to be a captivating fusion of past and present, inviting you to uncover its layers and create cherished memories in the heart of the Grand Duchy.`
    ),
    (
        `Madrid`,
        `Spain`,
        3320069,
        `Spanish`,
        `https://images.unsplash.com/photo-1509356428672-3589ea634248?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=871&q=80`,
        `euro (EUR)`,
        `Madrid Explored: Embracing Spain's Vibrant Capital`,
        `Navigating Madrid's Historical and Cultural Marvels`,
        `Madrid, the vibrant capital of Spain, invites you on a captivating journey through its rich history and dynamic culture. This guide leads you through the majestic halls of the Royal Palace, where regal elegance and opulent décor narrate centuries of Spanish monarchy, and into the artistic sanctuary of the Prado Museum, home to masterpieces that span the ages. Wander through the bustling Puerta del Sol, a central hub where city life converges, and immerse yourself in the captivating stories of the Reina Sofia Museum's modern art collection. Discover the serenity of Retiro Park, a lush escape amidst the urban landscape, and as you explore Madrid's neighborhoods, you'll uncover the essence of a city that pays homage to its heritage while embracing contemporary vitality.`,
        `Beyond the Facades: Embracing Modern Charms`,
        `While Madrid's historical landmarks are captivating, the city's modern spirit offers an exciting contrast. Immerse yourself in the innovative atmosphere of Matadero Madrid, a former slaughterhouse transformed into a cultural center where art, theater, and creativity flourish. Stroll along the upscale Gran Vía, a boulevard lined with theaters, boutiques, and cafes, and delve into the contemporary art scene at the CaixaForum, an architectural gem that hosts thought-provoking exhibitions. Amidst Madrid's architectural splendor, the city's modernity adds an extra layer of excitement to your exploration.`,
        `Embracing Madrid's Flavors and Traditions`,
        `To fully embrace Madrid's essence, indulge in its culinary treasures and cherished customs. Savor traditional Spanish dishes like «paella», a flavorful rice dish, or «tapas», an array of small bites that capture the essence of Spanish flavors. Engage with the locals at the bustling Mercado de San Miguel, where a diverse range of gourmet offerings create a feast for the senses. Immerse yourself in the festive atmosphere of Madrid's annual San Isidro Festival, a celebration of music, dance, and gastronomy that honors the city's patron saint. As the sun sets over the Puerta de Alcalá, take a leisurely stroll along the Gran Via's illuminated streets, where the city's lights come alive, reflecting the harmonious blend of Madrid's historical legacy and its modern vibrancy. Madrid's allure lies in its ability to be a captivating fusion of tradition and innovation, inviting you to uncover its layers and create cherished memories in the heart of Spain.`
    ),
    (
        `Minsk`,
        `Belarus`,
        2020133,
        `Belarusian, Russian`,
        `https://images.unsplash.com/photo-1597986728524-76be10541f58?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80`,
        `rouble (BYN)`,
        `Minsk Explored: Embracing Belarus's Enigmatic Capital`,
        `Navigating Minsk's Historical and Cultural Enrichment`,
        `Minsk, the enigmatic capital of Belarus, welcomes you to embark on a captivating journey through its rich history and diverse cultural tapestry. This guide leads you through the poignant echoes of World War II at the Mound of Glory, a solemn memorial honoring fallen soldiers, and into the grandeur of Independence Square, a bustling center where monuments and modernity converge. Wander through the serene beauty of Gorky Park, an expansive green oasis that invites leisure and reflection, and immerse yourself in the artistic treasures of the National Art Museum. Discover the charm of the Troitskoye Predmestye, an ancient neighborhood where the past harmonizes with contemporary life, and as you explore Minsk's neighborhoods, you'll uncover the essence of a city that values tradition while embracing a modern outlook.`,
        `Beyond the Facades: Embracing Modern Flair`,
        `While Minsk's historical charm is captivating, the city's modern pulse offers a unique contrast. Immerse yourself in the modern cultural hub of Oktyabrskaya Square, where theaters, galleries, and cafes create a lively atmosphere for artistic exploration. Stroll along the vibrant streets of Nemiga, a bustling area where shopping, dining, and entertainment intertwine, and delve into the contemporary art scene at the Ў Gallery of Contemporary Art. Amidst Minsk's architectural beauty, the city's modern vibrancy adds an extra layer of intrigue to your exploration.`,
        `Embracing Minsk's Flavors and Traditions`,
        `To fully embrace Minsk's essence, indulge in its culinary treasures and cherished customs. Savor traditional Belarusian dishes like «draniki», potato pancakes, or «machanka», a hearty meat stew. Engage with the locals at the bustling Komarovka Market, where fresh produce, regional delicacies, and bustling energy create an authentic Belarusian experience. Immerse yourself in the festive atmosphere of Minsk's Victory Day Parade, a commemoration of triumph and unity. As the sun sets over the Svisloch River, take a leisurely stroll across the Troitsky Bridge, where the city's lights reflect on the water's surface, symbolizing the harmonious blend of Minsk's historical roots and its modern allure. Minsk's allure lies in its ability to be a captivating fusion of past and present, inviting you to uncover its layers and create cherished memories in the heart of Belarus.`,
    ),
    (
        `Monaco`,
        `Monaco`,
        31109,
        `French`,
        `https://images.pexels.com/photos/17346705/pexels-photo-17346705/free-photo-of-sea-city-vacation-water.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1`,
        `euro (EUR)`,
        `Monaco City Explored: Embracing the Glamour of the Principality`,
        `Navigating Monaco City's Luxurious and Cultural Charms`,
        `Monaco City, the epitome of luxury nestled on the Mediterranean coast, welcomes you to embark on a captivating journey through its opulent history and cultural allure. This guide leads you through the grandeur of the Prince's Palace, a symbol of sovereignty that overlooks the glittering harbor, and into the elegance of the Monaco Cathedral, where royal weddings and princely ceremonies echo through time. Wander through the narrow streets of the Old Town, where charming boutiques and cafes invite exploration, and immerse yourself in the artistic treasures of the Nouveau Musée National de Monaco. Discover the serenity of the Exotic Garden, a haven of rare flora atop a cliff, and as you traverse Monaco City's districts, you'll uncover the essence of a place that celebrates tradition while embodying a modern sense of sophistication.`,
        `Beyond the Glitz: Embracing Understated Beauty`,
        `While Monaco City's glamour is captivating, the city's subtler beauty offers a captivating contrast. Immerse yourself in the tranquility of the Japanese Garden, an oasis of calm amidst the urban hubbub, and stroll along the stunning Larvotto Beach, where the azure waters meet pristine sand. Delve into the contemporary art scene at the Grimaldi Forum, where international exhibitions stimulate thought and creativity. Amidst Monaco City's lavish exterior, its understated elegance adds an extra layer of fascination to your exploration.`,
        `Embracing Monaco City's Flavors and Traditions`,
        `To fully embrace Monaco City's essence, indulge in its culinary delights and cherished customs. Savor Mediterranean-inspired dishes like «barbajuan», a delectable spinach and cheese pastry, or «socca», a savory chickpea flour crepe. Engage with the locals at the vibrant Condamine Market, where fresh produce, artisanal products, and local charm create an authentic sensory experience. Immerse yourself in the festive atmosphere of Monaco's Grand Prix, a renowned motor racing event that adds excitement to the city's elegant ambiance. As the sun sets over Port Hercule, take a leisurely stroll along the waterfront, where the city's lights illuminate the harbor, reflecting the harmonious blend of Monaco City's timeless heritage and its modern allure. Monaco City's allure lies in its ability to be a captivating blend of glitz and understated beauty, inviting you to uncover its layers and create cherished memories in this luxurious principality.`,
    ),
    (
        ``,
        ``,
        ,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
    ),
    (
        ``,
        ``,
        ,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
    ),
    (
        ``,
        ``,
        ,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
    ),
    (
        ``,
        ``,
        ,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
        ``,
    );

-- these are just to use before user creation and login is allowed:
INSERT INTO `user` (`first_name`, `last_name`, `username`, `password`)
VALUES
    (`Maria`, `Müller`, `maria_mueller`, `MariaMueller`),
    (`José`, `Ortiz`, `jose_ortiz`, `JoseOrtiz`),
    (`Alexandra`, `Green`, `alexandra_green`, `AlexandraGreen`);